Upgrade django-rq from 2.3.1 to 2.3.2
The error below was found in hedera's logs:

File "/usr/local/lib/python3.7/site-packages/django_rq/urls.py", line 3, in <module>
from . import views
File "/usr/local/lib/python3.7/site-packages/django_rq/views.py", line 12, in <module>
from rq.exceptions import NoSuchJobError, UnpickleError
ImportError: cannot import name 'UnpickleError' from 'rq.exceptions' (/usr/local/lib/python3.7/site-packages/rq/exceptions.py)
[2020-07-02 19:49:04 +0000] [89] [INFO] Worker exiting (pid: 89)

Turns out that "UnpickleError" is no longer present in RQ >= 1.4.0
See https://github.com/rq/django-rq/commit/9f7dbe32623b085ea85799fc20dc0fb36b9903ab